### ISSUE TITLE
Parallelized Training?

### ISSUE THREAD

**Issue by haighal** [tech-srl/code2seq#10]
Hey!

I'm a master's student at training a model on `java-large` (I'm just starting by trying to reproduce the results), and, unsurprisingly, it's taking forever on a single GPU.  When you trained the model for 52 epochs on `java-large`, did you distribute training?  If not, approximately how long did it take you?  And if you did - is there any chance you'd be willing to release your code that does it?

I would really appreciate it!  I'm planning to train the model on a Python dataset and would love to be able to train more quickly later on.

Thanks,
Alex

**Comment by urialon** [comment]
Hi Alex,
Thank you for your interest in code2seq!

1. We did not distribute training, just trained the model on a single Tesla V100 GPU for 52 epochs (a p3 instance in AWS).
2. This took about 5 days for getting almost all scores, and a few extra days for the final minor increase in the scores.
3. All code is released! The code and parameters in this repository are the same as in our training. 
4. For faster training with a minor score degradation, you can try the following changes (in `config.py`):
(a) Set `RANDOM_CONTEXTS` to `false`.
(b) `USE_MOMENTUM` to `false` (it uses Adam instead, which converges faster)
(c) In the file `preprocessing.sh`, take only 100 `MAX_CONTEXTS` instead of the default of 200.
(d) Decrease embedding sizes and vocabulary sizes.
5. You mentioned that you're trying to work on a python dataset: in our previous work, we noticed that python code is more difficult to learn (in general, not specifically for the code2seq task). We think that this is mainly because of the lack of type information; an additional cause is that Java code is usually cleaner in the top Github repositories in terms of naming conventions, having short and concise methods, etc.

Let me know how it works, and which hyperparameters gave you the most speed increase.

Best,
Uri

**Comment by haighal** [comment]
Thanks for the help! After 5 epochs, the performance was at

```
Accuracy: 0.30012
Precision: 0.58042, recall: 0.48426, F1: 0.52799
```

which is most of the way to your performance after 52 epochs (~7 points off the results from the pretrained model).  It's taking much longer than 5 days for me, but I think it's a result of network latency because the dataset is stored remotely.  I'm try storing the dataset locally first, and if that is still slow (I guess because of hardware), I'll look into the modifications you suggest.

Will keep you posted on how it goes!

Alex
