### ISSUE TITLE
translation on code2seq

### ISSUE THREAD

**Issue by shangqing-liu** [tech-srl/code2seq#19]
Hi,
When I use code2seq model to train a translation task on java dataset, the bleu is not promising, do you have any suggestions on this task?

thanks

**Comment by urialon** [comment]
Hi,
I can't help without knowing which data did you use,  did you change any parameters from the default values, and what does "not promising" mean...

You can try increasing the number of decoder layers (`config.NUM_DECODER_LAYERS`) to 2 and their size ( `config.DECODER_SIZE` ) to 512 [in the config](https://github.com/tech-srl/code2seq/blob/master/config.py) file. 
If the target NL sequences are long, it is **crucial** to increase `config.MAX_TARGET_PARTS`, otherwise the model will truncate the sequences to the current value.

More data always helps...

Best,
Uri
