### ISSUE TITLE
Manual Examination of Pretrained model is generating error.

### ISSUE THREAD

**Issue by nitishMehrotra** [tech-srl/code2seq#2]
When I try to run the pre trained model from S3 to manually examine the model following errors is coming:

<img width="1680" alt="screenshot 2019-02-15 at 3 58 39 pm" src="https://user-images.githubusercontent.com/3133988/52850855-950c8280-313a-11e9-84fd-731440756f3f.png">

**Comment by urialon** [comment]
Hmm, I'll check. In the meantime, can you please check your TensorFlow version? See the command line here:

https://github.com/tech-srl/code2vec/blob/master/README.md#requirements

Additionally, can you check if you can run the file reader.py as the main file?

**Comment by urialon** [comment]
Hi @nitishMehrotra ,
I believe that the problem is related to your python version 3.7, and to the warning in the second line of your screenshot.
It seems that your installed TensorFlow is not supported on python 3.7.
I suggest trying running it under python 3.6 (my preferred option) **or** upgrade TensorFlow to v1.13.0rc1.

See here:
https://github.com/tensorflow/tensorflow/issues/17022
and here:
https://github.com/tensorflow/tensorflow/issues/23410
