### ISSUE TITLE
How to decode?

### ISSUE THREAD

**Issue by ZhichaoOuyang** [tech-srl/code2seq#32]
Hello!
I want to know your experiment if the decoding phase also generates words one by one? 
In your paper, you use AST path to encode. However, there is no detailed introduction in the decoding stage. 
Is the word or a certain path generated during decoding, and then go to select the word?

**Comment by urialon** [comment]
Hi @ZhichaoOuyang ,
Thank you for your interest in code2seq!

Yes, the decoding phase generates words one-by-one. It actually decodes exactly the same as seq2seq models (explained here for example: [https://youtu.be/IxQtK2SjWWM](https://youtu.be/IxQtK2SjWWM)), 
with the only difference that the model computes attention over _paths_ rather than over _words_.

In every decoding step, the model computes a different weighted average (=attention) of the input paths, and use the weighted average to select the next word.

Let me know if you have any more questions.
Best,
Uri

**Comment by ZhichaoOuyang** [comment]
Therefore, when decoding, do you still weight the representation z_i of every path and the corresponding attention \alpha_i of each path to get a vector c_t, and then predict the word one by one just like standard NMT models? 

In other words, your model formula is the same as the encoder-decoder framework formula described in section 3.1 of your paper, except that z represents the path rather than input source words, right?

**Comment by urialon** [comment]
Yes, exactly!

**Comment by ZhichaoOuyang** [comment]
thanks, I got it.
