### ISSUE TITLE
Java parser invoke by default...

### ISSUE THREAD

**Issue by Pawan300** [tech-srl/code2seq#37]
We already trained model for Python150kExtractor, but it continuously using java parser and throwing this error?
We are using :
predictor=InteractivePredictor(config, model)
predictor.predict()
and got this error...(phew) 
_**_'{"errorMessage":"Encountered u_nexpected token: \\"import\\" \\"import\\"\\n    at line 1, column 20.\\n\\nWas expecting one of:\\n\\n    \\";\\"\\n    \\"<\\"\\n    \\"@\\"\\n    \\"abstract\\"\\n    \\"boolean\\"\\n    \\"byte\\"\\n    \\"char\\"\\n    \\"class\\"\\n    \\"default\\"\\n    \\"double\\"\\n    \\"enum\\"\\n    \\"final\\"\\n    \\"float\\"\\n    \\"int\\"\\n    \\"interface\\"\\n    \\"long\\"\\n    \\"native\\"\\n    \\"private\\"\\n    \\"protected\\"\\n    \\"public\\"\\n    \\"short\\"\\n_    \\"static\\"\\n    \\"strictfp\\"\\n    \\"synchronized\\"\\n    \\"transient\\"\\n    \\"void\\"\\n    \\"volatile\\"\\n    \\"{\\"\\n    \\"}\\"\\n    <IDENTIFIER>\\n\\n","errorType":"com.github.javaparser.ParseProblemException","stackTrace":["com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:242)","com.github.javaparser.JavaParser.parse(JavaParser.java:210)","MethodPaths.FeatureExtractor.parseFileWithRetries(FeatureExtractor.java:86)","MethodPaths.FeatureExtractor.extractFeatures(FeatureExtractor.java:49)","MethodPaths.ExtractFeaturesTask.extractSingleFile(ExtractFeaturesTask.java:140)","MethodPaths.ExtractionHandler.handleRequest(ExtractionHandler.java:49)","sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)"]}'_**_

**Comment by urialon** [comment]
Hi @Pawan300,
Thanks for your interest in code2seq!

Yeah, this is expected. 
The `InteractivePredictor` is using the [EXTRACTION_API](https://github.com/tech-srl/code2seq/blob/master/interactive_predict.py#L7) which is a deployed AWS Lambda Function that parses **Java**.

The Python extractor was only recently contributed by @stasbel , and was contributed as an "offline" extractor for the **already-parsed** python dataset called "Python150k".
Making the Python extractor work with InteractivePredictor requires implementing a python component that takes raw python programs, parses them, extracts paths using the same logic as the [Python150kExtractor](https://github.com/tech-srl/code2seq/tree/master/Python150kExtractor), and connecting this component to the InteractivePredictor either by an HTTP request (as it is [currently the case with the Java API](https://github.com/tech-srl/code2seq/blob/master/extractor.py#L18)) or directly by simply calling it (because both the InteractivePredictor and the PythonExtractor are written in Python).

Unfortunately, I don't think I have the capacity to do it myself anytime soon. If you manage to implement this yourself, I would happily adopt it into this project.

Best,
Uri

**Comment by Pawan300** [comment]
Thanks @urialon,
I think I got your point.
