### ISSUE TITLE
Code captioning 

### ISSUE THREAD

**Issue by MaryamVP** [tech-srl/code2seq#67]
Hello, I am not able to find the code captioning used in your paper here in the page. Can you please provide the python code doing that?

**Comment by urialon** [comment]
Hi @MaryamVP ,
Code captioning is performed using the exact same python code.

The only thing we did not release is the code that reads the CodeNN dataset and transforms it into our format, because we found this dataset to be noisy and we don't recommend using it.
See additional discussion here: #17

**Comment by YawWQ** [comment]
> Hi @MaryamVP ,
> Code captioning is performed using the exact same python code.
> 
> The only thing we did not release is the code that reads the CodeNN dataset and transforms it into our format, because we found this dataset to be noisy and we don't recommend using it.
> See additional discussion here: #17

Hi, sorry for bothering you again. I just want to know that, should we train the model from scratch and change the number of LSTM unit more longer, if we want to get the result of code captioning? I see that some parameters like EMBEDDINGS_SIZE in #17 are different from those in the default config.

**Comment by urialon** [comment]
Hi @YawWQ ,
Yes, some parameters are slightly different than the default in code
captioning, as described in #17 .
So, to reproduce, it requires to train the model from scratch on the CodeNN
data with those parameters.
